### ISSUE TITLE
您好，我在运行程序的时候出现了以下错误：

### ISSUE THREAD

**Issue by mzj123456** [marsmarcin/Siamese-Nets-for-Face-Reco#1]
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    loss_contrastive = criterion(output1,output2,label)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 133, in forward
    loss_contrastive = torch.mean((1-label) * torch.pow(euclidean_distance, 2) +
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 321, in __mul__
    return self.mul(other)
TypeError: mul received an invalid combination of arguments - got (Variable), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (Variable)
 * (torch.FloatTensor other)
      didn't match because some of the arguments have invalid types: (Variable)

Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x7fa52dcc1d68>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 333, in __del__
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 319, in _shutdown_workers
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
请问是什么原因呢

**Comment by marsmarcin** [comment]
因为有些python的版本会对数据的类型要求的很严格，我的python版本是3.6.0，你可以通过anaconda创建一个虚拟环境来验证
